import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const html = await readFile(new URL('../index.html', import.meta.url), 'utf8');
assert.equal((html.match(/<link rel="canonical"/g) ?? []).length, 1);
assert.match(html, /<title>AI Research Question Preflight \| Dystiny<\/title>/);
assert.match(html, /utm_content=hero_explore_topics/);
assert.match(html, /utm_content=hero_explore_technology/);
assert.match(html, /utm_content=hero_explore_science/);
assert.match(html, /utm_content=footer_explore_topics/);
assert.match(html, /"about": \[/);
assert.match(html, /<h1>Shape a broad idea into a stronger research question\.<\/h1>/);
assert.match(html, /does not save, send, or analyze/);
assert.match(html, /coarse 0–4 readiness signal/);
assert.equal((html.match(/name="evidence"/g) ?? []).length, 4);
assert.match(html, /Health evidence/);
assert.match(html, /medlineplus\.gov\/evaluatinghealthinformation\.html/);
assert.match(html, /data-evidence-note/);
assert.match(html, /destination question visibly includes/);
assert.match(html, /data-launch/);
assert.match(html, /tabindex="-1"/);
assert.match(html, /Write a question to continue/);
assert.equal((html.match(/class="example-link"/g) ?? []).length, 4);
assert.match(html, /utm_content=example_city_heat/);
assert.match(html, /Creative research path/);
assert.match(html, /utm_content=creative_research_path/);
assert.match(html, /si\.edu\/OpenAccess/);
assert.match(html, /separate observation from interpretation/i);
assert.match(html, /Event technology path/);
assert.match(html, /utm_content=event_ticketing_decision/);
assert.match(html, /utm_content=event_ticketing_explore/);
assert.match(html, /docs\.stripe\.com\/payments\/checkout/);
assert.match(html, /WCAG22\/Understanding\/target-size-minimum\.html/);
assert.match(html, /attendee data ownership/);
assert.match(html, /Visual evidence path/);
assert.match(html, /utm_content=visual_provenance_path/);
assert.match(html, /utm_content=visual_provenance_explore/);
assert.match(html, /spec\.c2pa\.org\/specifications/);
assert.match(html, /w3\.org\/WAI\/tutorials\/images/);
assert.match(html, /Separate observation/);
assert.match(html, /Matching-system evidence path/);
assert.match(html, /utm_content=matching_system_evidence/);
assert.match(html, /utm_content=matching_system_explore/);
assert.match(html, /nist\.gov\/itl\/ai-risk-management-framework/);
assert.match(html, /accessible-authentication-minimum\.html/);
assert.match(html, /Plan challenge and recovery/);
assert.doesNotMatch(html, /Clarity/i);

const jsonLd = html.match(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/);
assert.ok(jsonLd, 'WebApplication structured data is present');
assert.equal(JSON.parse(jsonLd[1])['@type'], 'WebApplication');
console.log('Static checks passed.');
